import "./styles/global.scss";

import type { Metadata } from "next";

import { Inter, Roboto } from "next/font/google";
import Header from "./components/Header/page";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Aula",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <>
          <Header />
          {children}
        </>
      </body>
    </html>
  );
}
